_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/fsx/detectron2/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  # Detectron1 uses smooth L1 loss with some magic beta values.
  # The defaults are changed to L1 loss in Detectron2.
  RPN:
    SMOOTH_L1_BETA: 0.1111
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 1.0
    POOLER_SAMPLING_RATIO: 2
    POOLER_TYPE: "ROIAlign"
  ROI_MASK_HEAD:
    POOLER_SAMPLING_RATIO: 2
    POOLER_TYPE: "ROIAlign"
INPUT:
  # no scale augmentation
  MIN_SIZE_TRAIN: (800, )
SOLVER:
  IMS_PER_BATCH: 2          # Can't fit 16 in memory
  BASE_LR: 0.0025             # 0.02 @ 16 = 0.01 @ 2
  STEPS: (480000, 640000)     # (60000, 80000) @ 16 = (120000, 160000) @ 2
  MAX_ITER: 720000           # 90000 @ 16 = 360000 @ 2
  WARMUP_ITERS: 125        # 1000 @ 16 = 250 @ 2
#  IMS_PER_BATCH: 4          # Can't fit 16 in memory
#  BASE_LR: 0.005             # 0.02 @ 16 = 0.01 @ 4
#  STEPS: (120000, 160000)     # (60000, 80000) @ 16 = (120000, 160000) @ 4
#  MAX_ITER: 360000           # 90000 @ 16 = 360000 @ 4
#  WARMUP_ITERS: 250        # 1000 @ 16 = 250 @ 4